### ISSUE TITLE
[Windows 10] Install/zip extract, data error: opengl32sw.dl

### ISSUE THREAD

**Issue by james-s-w-clark** [krogank9/WifiMouseServer#1]

**Comment by james-s-w-clark** [comment]
Installed worked on second attempt. Here was my process:
Install (fail, bad DLL)
Extract zip (fail, bad DLL)
Install (success!)

**Comment by krogank9** [comment]
Thanks for your report. I'm not sure why it worked the second time though, maybe that means it was just a fluke?

Did you have to download and install that DLL for it to work or just worked the second try?

opengl32sw.dll is supplied in both the portable and installer version, so it should have worked.

Also, when extracting the ZIP archive, dlls are hidden in the folder so you must right click extract it all into one folder instead of just dragging it out. EDIT: just changed it so DLLs are not hidden to avoid confusion.

**Comment by james-s-w-clark** [comment]
I didn't get download/install the missing dll.  it was strange that both the zip and the install missed it first time. I think in 7-zip I may have used "Ctrl+A" and then hit extract, to a folder on my desktop - so maybe that missed some hidden files, as you say. (I think there were multiple, now that I think about it).

**Comment by james-s-w-clark** [comment]
No missing files on .zip extraction now. I think you can close the issue.

Reran the install after an uninstall, worked fine too.

**Comment by krogank9** [comment]
I've just replaced the portable zip with a portable self extracting exe including all those dlls. Hopefully that works well.

**Comment by pradeepsimba** [comment]
How can I solve this issue ?

https://github.com/krogank9/WifiMouseServer/issues/8

**Comment by james-s-w-clark** [comment]
These issues seem unrelated. This one is stale, can be closed if it isn't already.
